version: '2'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    container_name: cadt-load-balance
    depends_on:
      - express-cadt
    environment:
      - NGINX_SERVER_NAME=localhost
      - EXPRESS_HOST_1=my-express-cadt-express-cadt-1
      - EXPRESS_HOST_2=my-express-cadt-express-cadt-2
      - EXPRESS_HOST_3=my-express-cadt-express-cadt-3
      - EXPRESS_PORT=4000
      - NGINX_MAX_BODY=100M
    ports:
      - 4000:4000
  express-cadt:
    build: .
    volumes:
      - .:/app
      - ./frontend/dist:/app/frontend/dist
      - ./frontend/node_modules:/app/frontend/node_modules
      - /app/node_modules
      - ./uploads:/app/uploads
    depends_on:
      - mongodb
      - redis
    scale: 3
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile-mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
  redis:
    image: redis:7.2.5
    container_name: cadt-redis
    ports:
      - 6379:6379
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:cadt-redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
volumes:
  mongodbdata:
