version: '2'
services:
  express-cadt:
    build: .
    container_name: express-cadt
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./uploads:/app/uploads
    depends_on:
      - mongodb
      - redis
  mongodb:
    image: mongo:7.0.12
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
  redis:
    image: redis:7.2.5
    container_name: cadt-redis
    ports:
      - 6379:6379
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:cadt-redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
volumes:
  mongodbdata:
